name: Auto-approve Release Please PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'release-please[bot]'
    steps:
      - name: Approve PR
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
        run: gh pr review --approve "${{ github.event.pull_request.html_url }}"

      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
        run: gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
